# assuming caps lock <-> ctrl
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# lazygit in popup 
bind-key -r g display-popup -E -d "#{pane_current_path}" -w 90% -h 90% -y S "lazygit"

# new panes open in existing directory
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# ideas / todos
# neovim in display-popup 
#   -> I just need to jump into files for a hot minute while I'm working on it
#   -> Make changes, and drop out
#   -> This would make sense alongside yazi or fzf to bring up file quickly
#   -> What if I don't know the file?
# gemini or other in a little popup
#   -> I don't want to come out of my TUI to quickly google/check something

