# assuming caps lock <-> ctrl
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# neovim in popup
bind-key -r v display-popup -E -d "#{pane_current_path}" -w 90% -h 90% -y S "nvim ."

# lazygit in popup
bind-key -r g display-popup -E -d "#{pane_current_path}" -w 90% -h 90% -y S "lazygit"

# session picker in popup
bind-key -r f display-popup -E -w 90% -h 90% -y S "sessions"

# new panes open in existing directory
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# ideas / todos
# -> I need a clearer indication of which mode I'm in when in nvim
# -> telescope or other for chasing function call chains through a codebase
# -> how do nvim users run debuggers
# -> clearer indications of which pane I'm currently in

# TODOs
# End of window session. NB: 1 window = 1 working session. For now, equates to 1 project only but introduce worktrees in future when a problem.
# If using stow, then it needs to own the entire directory in order to mirror it. I don't think this is going to work for directories that have files from multiple sources.
# lazygit support for accept incoming or accept target -> easy interface for this!
